spring:
  security:
    user:
      name: bins
      password: flights
      roles: ADMIN
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/flight-bin
    username: skyq_qms
    password: skyq_qms
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true

server:
  servlet:
    context-path: /api